name: Update JSON on JSONBin.io

on:
  repository_dispatch:
    types: [update-json]

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update JSON on JSONBin.io
      env:
        API_KEY: ${{ secrets.JSONBIN_API_KEY }}
        BIN_ID: ${{JSONBIN_ID}}
      run: |
        curl -X PUT \
        -H "Content-Type: application/json" \
        -H "X-Master-Key: $API_KEY" \
        -d '${{ github.event.client_payload.new_data }}' \
        https://api.jsonbin.io/v3/b/$BIN_ID
